[package]
name = "coingecko"
version = "0.1.0"
authors = ["ecklf <ecklf@icloud.com>"]
keywords = ["coingecko", "api"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.6.0", features = ["full"] }
reqwest = { version = "0.11.3", features = ["json"] }
anyhow = "1.0.40"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
chrono = "0.4.19"

[dev-dependencies]
tokio-test = "*"
